#!/bin/bash

echo "📦 NCDHHS PDF Q&A - Manual Amplify Upload Guide"
echo "=============================================="
echo ""
echo "✅ Build completed successfully!"
echo "📁 Build files location: frontend/build/"
echo "📦 Deployment package: ncdhhs-frontend-build.zip"
echo ""
echo "🚀 To deploy to AWS Amplify:"
echo ""
echo "1. Open AWS Amplify Console:"
echo "   https://console.aws.amazon.com/amplify/"
echo ""
echo "2. Click 'New app' → 'Host web app'"
echo ""
echo "3. Choose 'Deploy without Git provider'"
echo ""
echo "4. Upload the zip file:"
echo "   📦 ncdhhs-frontend-build.zip"
echo ""
echo "5. Configure these environment variables:"
echo "   REACT_APP_API_URL = http://ncdhhs-pdf-qa-dev-alb-940310890.us-east-1.elb.amazonaws.com"
echo "   REACT_APP_ENVIRONMENT = production"
echo "   REACT_APP_VERSION = 4.0.0"
echo ""
echo "6. Click 'Save and deploy'"
echo ""
echo "🌐 Your app will be available at a URL like:"
echo "   https://main.d1234567890.amplifyapp.com"
echo ""
echo "⏱️  Deployment typically takes 2-3 minutes"
echo ""
echo "🎉 That's it! Your frontend will be live on AWS!"

